### ISSUE TITLE
GSD_CMS error Failed to fetch files.

### ISSUE THREAD

**Issue by nkcr** [directus/gatsby-source#27]
It happens that I had to **upload at least a PDF file** in order to avoid the following error when running `gatsby develop`:

```
GSD_CMS info Fetching all files...
 ERROR
GSD_CMS error Failed to fetch files.
 ERROR
GSD_CMS error Did you grant READ permissions?
 ERROR
GSD_CMS error Failed to build Directus nodes {
  e: TypeError: Reduce of empty array with no initial value
      at Array.reduce (<anonymous>)
      at DirectusService.<anonymous> (/Users/nkcr/Desktop/gatsby/tutorial-part-four/node_modules/@directus/gatsby-source-directus/directus-service/index.js:202:29)
      at Generator.next (<anonymous>)
      at fulfilled (/Users/nkcr/Desktop/gatsby/tutorial-part-four/node_modules/@directus/gatsby-source-directus/directus-service/index.js:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
}
warn The @directus/gatsby-source-directus plugin has generated no Gatsby nodes. Do you need it?
```

I know this is partially described in the "Known limitations" section. I'm just leaving this there in case that could help others.

**Comment by loganwishartcraig** [comment]
This could be related to PR #28

**Comment by loganwishartcraig** [comment]
PR #28 released.

Gonna close this, thanks for the issue though!
